name: test-and-deploy-project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-build-and-deploy:
    uses: ./.github/workflows/test.yml
  
  deploy-project:
    runs-on: ubuntu-latest
    needs: call-build-and-deploy
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3

    - name: â˜ï¸ Download build directory
      uses: actions/download-artifact@v3
      with:
        name: build
        path: build/

    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages 
        folder: build
      
