# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Project Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build-and-test:
    name: build and test the app
    runs-on: ubuntu-latest
    steps:
    - name:  ğŸ›ï¸ Checkout repository
      uses: actions/checkout@v3

    - name: ğŸ”§ Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: ğŸ”§ install npm
      run: npm ci

    - name: ğŸ”§ Build project
      run: npm run build --if-present

    - name: ğŸ” Test project
      run: npm test

    - name: Upload build artifact  
      if: github.action == 'workflow_call'
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/
