name: project-tests
on:
  workflow_call:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: build and test the app
    runs-on: ubuntu-latest
    steps:
    - name:  ğŸ›ï¸ Checkout repository
      uses: actions/checkout@v3

    - name: ğŸ”§ Setup Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: ğŸ”§ install npm
      run: npm ci

    - name: ğŸ”§ Build project
      run: npm run build --if-present

    - name: ğŸ” Test project
      run: npm test
    
    - name: â˜ï¸ Upload the build directory
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/
        retention-days: 1

